export const EmployeeToggle = [
  '/employees/masters/dashboard',
  '/employees/masters/create-employee-step-one',
  '/employees/masters/create-employee-step-two',
  '/employees/masters/create-employee-step-three',
  '/employees/masters/create-employee-step-four',
  '/employees/masters/employee-list',
  '/employees/masters/employee-profile',
  '/employees/master/organization-structure',
  '/employees/master/employee-exit',
  '/employees/master/full-and-final',
  '/employees/master/full-and-final-step-one',
  '/employees/master/full-and-final-step-two',
  '/employees/master/full-and-final-step-three',
  '/employees/master/full-and-final-step-four',
  '/employees/administration/bulk-excel-upload',
  '/employees/administration/bulk-excel-upload-step-one',
  '/employees/administration/bulk-excel-upload-step-two',
  '/employees/administration/bulk-excel-upload-step-three',
  '/employees/administration/bulk-excel-upload-step-four',
  '/employees/administration/bulk-profile-photo-upload',
  '/employees/administration/bulk-profile-photo-upload-step-one',
  '/employees/administration/bulk-profile-photo-upload-step-two',
  '/employees/administration/bulk-profile-photo-upload-step-three',
  '/employees/administration/bulk-document-upload',
  '/employees/administration/bullk-document-upload-step-one',
  '/employees/administration/bullk-document-upload-step-two',
  '/employees/setting/publish-form',
  '/employees/setting/publish-form-inner',
  '/employees/setting/code-setting',
  '/employees/setting/master-setting',
];

export const organizationToggle = [
  '/organization/company',
  '/organization/legal-entity',
  '/organization/business-unit',
  '/organization/location',
  '/organization/bank',
];

export const schemeToggle = [
  '/scheme/attendance/capture-method',
  '/scheme/attendance/create-capture-method',
  '/scheme/attendance/capture-method/assign-employee',
  '/scheme/attendance/attendance-tracking',
  '/scheme/attendance/create-attendance-tracking',
  '/scheme/attendance/attendance-tracking/assign-employee',
  '/scheme/attendance/biometric-device',
  '/scheme/attendance/create-biometric-device',
  '/scheme/attendance/biometric-device/assign-employee',
  '/scheme/attendance/geo-fancing',
  '/scheme/attendance/create-geo-fancing',
  '/scheme/attendance/geo-fancing/assign-employee',
  '/scheme/attendance/ip-range',
  '/scheme/attendance/create-ip-range',
  '/scheme/attendance/ip-range/assign-employee',
  '/scheme/overtime',
  '/scheme/OverTimemorepage/OverTimeStepone',
  '/scheme/overtime/assign-employee',
  '/scheme/compoff',
  '/scheme/CompOffStepone/CompOffStepone',
  '/scheme/compoff/assign-employee',
  '/scheme/leave',
  '/scheme/leavepages/leave-step-one',
  '/scheme/leavepages/leave-entitle-setup',
  '/scheme/leavepages/leave-entitle-prorate',
  '/scheme/leavepages/leave-application-rule',
  '/scheme/leavepages/leave-eestriction-setting',
  '/scheme/leavepages/holiday-weekend',
  '/scheme/leavepages/leave-yearend',
  '/scheme/leavepages/leave-approval',
  '/scheme/leave/assign-employee',
];

export const timeAndAttendanceToggle = [
  '/time-and-attendance/dashboard',
  '/time-and-attendance/shift-and-day',
  '/time-and-attendance/create-shift',
  '/time-and-attendance/create-weekly-off',
  '/time-and-attendance/holiday-list',
  '/time-and-attendance/shift-and-day-assign',
  '/time-and-attendance/shift-and-day-calender',
  '/time-and-attendance/shift-schedule-and-pattern',
  '/time-and-attendance/configure-new-pattern',
  '/time-and-attendance/attendance-management',
  '/time-and-attendance/month-register',
  '/time-and-attendance/regularization-approval',
  '/time-and-attendance/overtime',
  '/time-and-attendance/overtime-approval',
];

export const leaveToggle = [
  '/leave/dashboard',
  '/leave/leave-balance',
  '/leave/leave-approval',
  '/leave/leave-balance-correction',
  '/leave/comp-off',
  '/leave/comp-off-approval',
  '/leave/leave-type',
];

export const statutoryToggle = [
  '/statutory/pfconfiguration',
  '/statutory/pfconfiguration/create-pfconfiguration',
  '/statutory/esicconfiguration',
  '/statutory/esicconfiguration/create-esicconfiguration',
  '/statutory/lwfconfiguration',
  '/statutory/lwfconfiguration/create-lwfconfiguration',
  '/statutory/ptconfiguration',
  '/statutory/create-ptconfiguration',
  '/statutory/itconfiguration/tax-regime',
  '/statutory/itconfiguration/create-tax-regime',
  '/statutory/itconfiguration/cess-surcharge',
];

export const payrollToggle = [
  '/payroll/dashboard',
  '/payroll/compensation',
  '/payroll/salary-setup',
  '/payroll/process-payroll',
  '/payroll/process-payroll/view-pay-register',
  '/payroll/process-payroll/manage-payslip',
  '/payroll/earning-deduction',
  '/payroll/earning-deduction/add-earning-deduction',
  '/payroll/advance-loan',
  '/payroll/advance-loan/add-advance',
  '/payroll/manage-tds',
  '/payroll/setting/salary-components',
  '/payroll/setting/salary-components/add-earning-component',
  '/payroll/setting/salary-template',
  '/payroll/setting/salary-template/add-salary-template',
  '/payroll/setting/pay-period',
  '/payroll/setting/pay-period/pay-period-edit',
  '/payroll/setting/gratuity',
  '/payroll/setting/tds/investment',
  '/payroll/setting/tds/tax-saving-scheme',
];

export const expenseAndReimbursementToogle = [
  '/expense-reimbursement/expense-trip',
  '/expense-reimbursement/expense-trip/reimbursement',
  '/expense-reimbursement/reimbursement-approval',
  '/expense-reimbursement/expense-trip/reimbursement-request',
  '/expense-reimbursement/expense-type',
  '/expense-reimbursement/approval-chain',
];

export const letterToggle = [
  '/letter/generate',
  '/letter/generate/step-one',
  '/letter/generate/step-two',
  '/letter/generate/step-three',
  '/letter/generate/step-four',
  '/letter/letter-template',
  '/letter/letter-template/step-one',
  '/letter/letter-template/step-two',
  '/letter/letter-template/step-three',
  '/letter/letter-template/step-four',
  '/letter/setting',
];

export const assetsToggle = [
  '/assets/addassignment-asset',
  '/assets/category',
  '/assets/assigned-list',
  '/assets/assigned-list/create-asset',
];

export const helpdeskToggle = [
  '/helpdesk/ticket',
  '/helpdesk/tickets-chat',
  '/helpdesk/setting/category',
  '/helpdesk/setting/status',
];

export const settingsToggle = [
  '/setting/user-roles-permission',
  '/setting/User-roles-permission-step-one',
  '/setting/User-roles-permission-step-Two',
  '/setting/email-alert',
  '/setting/process-cheklist',
  '/setting/process-cheklist-step-two',
  '/setting/praise-badge',
  '/setting/core-value',
];
