import userImage from '../../Assets/images/user8.png';
import userImage1 from '../../Assets/images/user1.png';
import userImage2 from '../../Assets/images/user2.png';
import userImage3 from '../../Assets/images/user3.png';
import userImage4 from '../../Assets/images/user4.png';
export const EmployeeData = {
  getProductsData() {
    return [
      {
        id: '1000',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage,
      },
      {
        id: '1001',
        name: 'Kaushik Raval',
        department: 'Web Designer',
        designation: 'Sr. Web Designer',
        location: 'Katargam',
        image: userImage3,
      },
      {
        id: '1002',
        name: 'Manish Gondaliya',
        department: 'Developemt',
        designation: 'Sr. Frontend Developer',
        location: 'Katargam',
        image: userImage2,
      },
      {
        id: '1003',
        name: 'Mansi Kothiya',
        department: 'Developemt',
        designation: 'Frontend Developer',
        location: 'Katargam',
        image: userImage1,
      },
      {
        id: '1004',
        name: 'Vishal Tank',
        department: 'Web Designer',
        designation: 'Web Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1005',
        name: 'Dhaval Radadiya',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Katargam',
        image: userImage1,
      },
      {
        id: '1006',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
      {
        id: '1007',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage3,
      },
      {
        id: '1008',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1009',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage1,
      },
      {
        id: '1010',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
      {
        id: '1011',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage3,
      },
      {
        id: '1012',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1013',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage1,
      },
      {
        id: '1014',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
      {
        id: '1015',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage3,
      },
      {
        id: '1016',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1017',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
      {
        id: '1018',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1019',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
      {
        id: '1020',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage3,
      },
      {
        id: '1021',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage4,
      },
      {
        id: '1022',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage1,
      },
      {
        id: '1023',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage3,
      },
      {
        id: '1024',
        name: 'Chintan Raval',
        department: 'Designer',
        designation: 'Sr. UI/UX Designer',
        location: 'Adajan',
        image: userImage2,
      },
    ];
  },

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  },
};
